import { eContractid, IReserveParams } from "../../helpers/types";

import {
  rateStrategyVolatileTwo,
  rateStrategyStableTwo,
  rateStrategyVolatileOne,
  rateStrategyVolatileBTC,
  rateStrategyStableThree,
} from "./rateStrategies";

export const strategyMBTC: IReserveParams = {
  strategy: rateStrategyVolatileBTC,
  baseLTVAsCollateral: "5500",
  liquidationThreshold: "8500",
  liquidationBonus: "11000",
  liquidationProtocolFee: "1000",
  borrowingEnabled: true,
  stableBorrowRateEnabled: false,
  flashLoanEnabled: true,
  reserveDecimals: "18",
  aTokenImpl: eContractid.AToken,
  reserveFactor: "3000",
  supplyCap: "0",
  borrowCap: "60",
  debtCeiling: "0",
  borrowableIsolation: false,
};

export const strategyWBTC: IReserveParams = {
  strategy: rateStrategyVolatileBTC,
  baseLTVAsCollateral: "5500",
  liquidationThreshold: "8500",
  liquidationBonus: "11000",
  liquidationProtocolFee: "1000",
  borrowingEnabled: true,
  stableBorrowRateEnabled: false,
  flashLoanEnabled: true,
  reserveDecimals: "18",
  aTokenImpl: eContractid.AToken,
  reserveFactor: "3000",
  supplyCap: "0",
  borrowCap: "30",
  debtCeiling: "0",
  borrowableIsolation: false,
};

export const strategyMETH: IReserveParams = {
  strategy: rateStrategyVolatileTwo,
  baseLTVAsCollateral: "7500",
  liquidationThreshold: "8000",
  liquidationBonus: "10500",
  liquidationProtocolFee: "0",
  borrowingEnabled: false,
  stableBorrowRateEnabled: false,
  flashLoanEnabled: false,
  reserveDecimals: "18",
  aTokenImpl: eContractid.AToken,
  reserveFactor: "3000",
  supplyCap: "0",
  borrowCap: "4000",
  debtCeiling: "0",
  borrowableIsolation: false,
};

// export const strategyMUSDC: IReserveParams = {
//   strategy: rateStrategyStableOne,
//   baseLTVAsCollateral: "8250",
//   liquidationThreshold: "8500",
//   liquidationBonus: "10400",
//   liquidationProtocolFee: "1000",
//   borrowingEnabled: true,
//   stableBorrowRateEnabled: true,
//   flashLoanEnabled: false,
//   reserveDecimals: "6",
//   aTokenImpl: eContractid.AToken,
//   reserveFactor: "1000",
//   supplyCap: "2000000000",
//   borrowCap: "0",
//   debtCeiling: "0",
//   borrowableIsolation: true,
// };

export const strategyMUSDC: IReserveParams = {
  strategy: rateStrategyStableThree,
  baseLTVAsCollateral: "7500",
  liquidationThreshold: "9000",
  liquidationBonus: "10500",
  liquidationProtocolFee: "1000",
  borrowingEnabled: true,
  stableBorrowRateEnabled: false,
  flashLoanEnabled: true,
  reserveDecimals: "6",
  aTokenImpl: eContractid.AToken,
  reserveFactor: "3000",
  supplyCap: "0",
  borrowCap: "1000000",
  debtCeiling: "0",
  borrowableIsolation: false,
};

// export const strategyMUSDT: IReserveParams = {
//   strategy: rateStrategyStableOne,
//   baseLTVAsCollateral: "8250",
//   liquidationThreshold: "8500",
//   liquidationBonus: "10400",
//   liquidationProtocolFee: "1000",
//   borrowingEnabled: true,
//   stableBorrowRateEnabled: true,
//   flashLoanEnabled: false,
//   reserveDecimals: "6",
//   aTokenImpl: eContractid.AToken,
//   reserveFactor: "1000",
//   supplyCap: "2000000000",
//   borrowCap: "0",
//   debtCeiling: "0",
//   borrowableIsolation: true,
// };

export const strategyMUSDT: IReserveParams = {
  strategy: rateStrategyStableThree,
  baseLTVAsCollateral: "7500",
  liquidationThreshold: "9000",
  liquidationBonus: "10500",
  liquidationProtocolFee: "1000",
  borrowingEnabled: true,
  stableBorrowRateEnabled: false,
  flashLoanEnabled: true,
  reserveDecimals: "6",
  aTokenImpl: eContractid.AToken,
  reserveFactor: "3000",
  supplyCap: "0",
  borrowCap: "1000000",
  debtCeiling: "0",
  borrowableIsolation: false,
};

export const strategyMORDI: IReserveParams = {
  strategy: rateStrategyVolatileTwo,
  baseLTVAsCollateral: "0",
  liquidationThreshold: "0",
  liquidationBonus: "0",
  liquidationProtocolFee: "2000",
  borrowingEnabled: false,
  stableBorrowRateEnabled: false,
  flashLoanEnabled: false,
  reserveDecimals: "18",
  aTokenImpl: eContractid.AToken,
  reserveFactor: "3000",
  supplyCap: "0",
  borrowCap: "0",
  debtCeiling: "0",
  borrowableIsolation: false,
};

export const strategySOLVBTC: IReserveParams = {
  strategy: rateStrategyVolatileBTC,
  baseLTVAsCollateral: "5000",
  liquidationThreshold: "8000",
  liquidationBonus: "11500",
  liquidationProtocolFee: "1000",
  borrowingEnabled: true,
  stableBorrowRateEnabled: false,
  flashLoanEnabled: true,
  reserveDecimals: "18",
  aTokenImpl: eContractid.AToken,
  reserveFactor: "3000",
  supplyCap: "0",
  borrowCap: "300",
  debtCeiling: "0",
  borrowableIsolation: false,
};

export const strategyMERL: IReserveParams = {
  strategy: rateStrategyVolatileTwo,
  baseLTVAsCollateral: "2000",
  liquidationThreshold: "8000",
  liquidationBonus: "12000",
  liquidationProtocolFee: "2000",
  borrowingEnabled: false,
  stableBorrowRateEnabled: false,
  flashLoanEnabled: false,
  reserveDecimals: "18",
  aTokenImpl: eContractid.AToken,
  reserveFactor: "3000",
  supplyCap: "30000000",
  borrowCap: "0",
  debtCeiling: "100000000",
  borrowableIsolation: false,
};

export const strategyMSTONE: IReserveParams = {
  strategy: rateStrategyVolatileTwo,
  baseLTVAsCollateral: "0",
  liquidationThreshold: "0",
  liquidationBonus: "0",
  liquidationProtocolFee: "1000",
  borrowingEnabled: false,
  stableBorrowRateEnabled: false,
  flashLoanEnabled: false,
  reserveDecimals: "18",
  aTokenImpl: eContractid.AToken,
  reserveFactor: "3000",
  supplyCap: "0",
  borrowCap: "0",
  debtCeiling: "0",
  borrowableIsolation: false,
};
